# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 120)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setSizeGripEnabled(True)
        MainWindow.setModal(True)
        self.FirstR = QtWidgets.QSpinBox(MainWindow)
        self.FirstR.setGeometry(QtCore.QRect(0, 90, 71, 31))
        self.FirstR.setMinimum(1)
        self.FirstR.setObjectName("FirstR")
        self.FinalR = QtWidgets.QSpinBox(MainWindow)
        self.FinalR.setGeometry(QtCore.QRect(70, 90, 61, 31))
        self.FinalR.setMinimum(1)
        self.FinalR.setMaximum(100)
        self.FinalR.setObjectName("FinalR")
        self.t1 = QtWidgets.QTextBrowser(MainWindow)
        self.t1.setGeometry(QtCore.QRect(70, 60, 61, 31))
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QTextBrowser(MainWindow)
        self.t2.setGeometry(QtCore.QRect(0, 60, 71, 31))
        self.t2.setObjectName("t2")
        self.calc = QtWidgets.QPushButton(MainWindow)
        self.calc.setGeometry(QtCore.QRect(130, 60, 75, 62))
        self.calc.setObjectName("calc")
        self.XP = QtWidgets.QLabel(MainWindow)
        self.XP.setGeometry(QtCore.QRect(200, 60, 421, 61))
        self.XP.setObjectName("XP")
        self.dif1 = QtWidgets.QRadioButton(MainWindow)
        self.dif1.setGeometry(QtCore.QRect(0, 30, 156, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dif1.setFont(font)
        self.dif1.setChecked(True)
        self.dif1.setObjectName("dif1")
        self.textBrowser = QtWidgets.QTextBrowser(MainWindow)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 624, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.dif2 = QtWidgets.QRadioButton(MainWindow)
        self.dif2.setGeometry(QtCore.QRect(156, 30, 156, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dif2.setFont(font)
        self.dif2.setObjectName("dif2")
        self.dif3 = QtWidgets.QRadioButton(MainWindow)
        self.dif3.setGeometry(QtCore.QRect(312, 30, 156, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dif3.setFont(font)
        self.dif3.setChecked(False)
        self.dif3.setObjectName("dif3")
        self.dif4 = QtWidgets.QRadioButton(MainWindow)
        self.dif4.setGeometry(QtCore.QRect(468, 30, 156, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dif4.setFont(font)
        self.dif4.setChecked(False)
        self.dif4.setObjectName("dif4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Xp Calculator"))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Calculate XP</p></body></html>"))
        self.t1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Last round</p></body></html>"))
        self.t2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">First round</p></body></html>"))
        self.calc.setText(_translate("MainWindow", "Calculate"))
        self.XP.setText(_translate("MainWindow", "TextLabel"))
        self.dif1.setText(_translate("MainWindow", "Beginner"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Map difficulty</span></p></body></html>"))
        self.dif2.setText(_translate("MainWindow", "Intermediate"))
        self.dif3.setText(_translate("MainWindow", "Advanced"))
        self.dif4.setText(_translate("MainWindow", "Expert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
